version: 0.0
os: linux

files:
  - source:  / #인스턴스에 복사할 디렉터리 경로
    destination: /home/ubuntu/app #인스턴스에서 파일이 복사되는 위치
    overwrite: yes #복사할 위치에 파일이 있는경우 대체

permissions:
  - object: / #권한이 지정되는 파일 또는 디렉토리
    pattern: "**" #매칭되는 패턴에만 권한 부여
    owner: ubuntu #object의 소유자
    group: ubuntu #object의 그룹이름

hooks:
  AfterInstall: #기존 실행중이던 app을 종료시킴
    - location: scripts/stop.sh #hooks에서 실행할 스크립트 위치
      timeout: 60 #스크립트 실행에 허용되는 최대시간이며, 넘으면 배포 실패로 간주
      runas: ubuntu # 스크립트를 실행하는 사용자
  ApplicationStart: # 새로운 app을 실행시킴
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu